name: airline_scraping

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    
jobs:
  airline-scrape:
    runs-on: macOS-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - name: Start time
      run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2   
    - name: Install packages
      run: |
        install.packages("rvest", dependencies = TRUE)
        install.packages("tidyverse", dependencies = TRUE)
        install.packages("mongolite")
      shell: Rscript {0} 
    - name: Scrape Data Airline Quality
      run: Rscript airline_scraping.R
